from flask import Blueprint, request, jsonify
from pathlib import Path
from datetime import datetime, timezone
from services.groq_client import generate_text

describe_bp = Blueprint("describe", __name__)

PROMPT_FILE = Path(__file__).resolve().parent.parent / "prompts" / "describe_prompt.txt"


@describe_bp.route("/describe", methods=["POST"])
def describe():
    data = request.get_json(silent=True)

    if not data:
        return jsonify({"error": "Request body must be valid JSON"}), 400

    input_text = data.get("input_text")

    if input_text is None:
        return jsonify({"error": "input_text is required"}), 400

    if not isinstance(input_text, str):
        return jsonify({"error": "input_text must be a string"}), 400

    input_text = input_text.strip()

    if not input_text:
        return jsonify({"error": "input_text cannot be empty"}), 400

    if len(input_text) > 5000:
        return jsonify({"error": "input_text is too long"}), 400

    try:
        prompt_template = PROMPT_FILE.read_text(encoding="utf-8")
    except FileNotFoundError:
        return jsonify({"error": "describe prompt file not found"}), 500

    final_prompt = prompt_template.replace("{input_text}", input_text)

    try:
        generated_description = generate_text(final_prompt)

        return jsonify({
            "description": generated_description,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "is_fallback": False
        }), 200

    except Exception:
        fallback_description = (
            f"Audit description could not be generated by AI at this time. "
            f"Input received: {input_text}"
        )

        return jsonify({
            "description": fallback_description,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "is_fallback": True
        }), 200